apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - secret.yaml
  - entra-id-secret.yaml
  - saml-idp-secret.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - pdb.yaml
  - hpa.yaml
