"""Unit tests for BoilerplateDetector, DEFAULT_RULES, and BoilerplateSettings (TASK-US015-03)."""

from __future__ import annotations

from datetime import UTC, datetime

import pytest
from pydantic import ValidationError

from src.compression.boilerplate.detector import BoilerplateDetector
from src.compression.boilerplate.rules import DEFAULT_RULES, BoilerplateRule
from src.compression.boilerplate.settings import BoilerplateSettings
from src.compression.schemas.removed_chunk import RemovalReason
from src.retrieval.schemas.retrieved_chunk import ChunkMetadata, RetrievedChunk

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

_TS = datetime(2024, 1, 1, tzinfo=UTC)


def _meta(file_path: str = "a/b.py") -> ChunkMetadata:
    return ChunkMetadata(file_path=file_path, timestamp=_TS, author="tester")


def _chunk(
    chunk_id: str,
    content: str,
    source_id: str = "github",
    score: float = 0.9,
) -> RetrievedChunk:
    return RetrievedChunk(
        chunk_id=chunk_id,
        source_id=source_id,
        content=content,
        score=score,
        metadata=_meta(),
    )


# ---------------------------------------------------------------------------
# BoilerplateRule validation
# ---------------------------------------------------------------------------


class TestBoilerplateRuleValidation:
    def test_valid_pattern_accepted(self) -> None:
        rule = BoilerplateRule(name="test", pattern=r"\bfoo\b")
        assert rule.name == "test"

    def test_invalid_pattern_raises_validation_error(self) -> None:
        with pytest.raises(ValidationError):
            BoilerplateRule(name="bad", pattern=r"[unclosed")


# ---------------------------------------------------------------------------
# DEFAULT_RULES registry
# ---------------------------------------------------------------------------


class TestDefaultRules:
    def test_has_at_least_eight_rules(self) -> None:
        assert len(DEFAULT_RULES) >= 8

    def test_all_rules_enabled_by_default(self) -> None:
        assert all(r.enabled for r in DEFAULT_RULES)

    def test_all_rules_have_name_and_description(self) -> None:
        for rule in DEFAULT_RULES:
            assert rule.name, f"Rule missing name: {rule}"
            assert rule.description, f"Rule missing description: {rule.name}"

    def test_all_rule_names_are_unique(self) -> None:
        names = [r.name for r in DEFAULT_RULES]
        assert len(names) == len(set(names))


# ---------------------------------------------------------------------------
# BoilerplateDetector — matching_rule
# ---------------------------------------------------------------------------


class TestMatchingRule:
    def test_spdx_license_header(self) -> None:
        detector = BoilerplateDetector()
        result = detector.matching_rule("// SPDX-License-Identifier: MIT")
        assert result == "spdx_license_header"

    def test_copyright_header(self) -> None:
        detector = BoilerplateDetector()
        result = detector.matching_rule("// Copyright (c) 2024 Acme Corp")
        assert result == "copyright_header"

    def test_auto_generated_do_not_edit(self) -> None:
        detector = BoilerplateDetector()
        result = detector.matching_rule("// DO NOT EDIT — generated file")
        assert result == "auto_generated_warning"

    def test_auto_generated_this_file_was_generated(self) -> None:
        detector = BoilerplateDetector()
        result = detector.matching_rule("// This file was generated by build toolchain")
        assert result == "auto_generated_warning"

    def test_maven_build_output(self) -> None:
        detector = BoilerplateDetector()
        result = detector.matching_rule("[INFO] --- maven-compiler-plugin:3.8.0:compile")
        assert result == "maven_build_output"

    def test_package_lock_sha256(self) -> None:
        detector = BoilerplateDetector()
        result = detector.matching_rule('"integrity": "sha256-abc123"')
        assert result == "package_lock_metadata"

    def test_package_lock_sha512(self) -> None:
        detector = BoilerplateDetector()
        result = detector.matching_rule('"integrity": "sha512-xyz789"')
        assert result == "package_lock_metadata"

    def test_generated_proto_header(self) -> None:
        rule = next(r for r in DEFAULT_RULES if r.name == "generated_proto_header")
        detector = BoilerplateDetector(rules=[rule])
        result = detector.matching_rule("// Code generated by protoc-gen-go v2.0")
        assert result == "generated_proto_header"

    def test_openapi_generated_header(self) -> None:
        rule = next(r for r in DEFAULT_RULES if r.name == "openapi_generated_header")
        detector = BoilerplateDetector(rules=[rule])
        result = detector.matching_rule(
            "// This class is auto generated by OpenAPI Generator"
        )
        assert result == "openapi_generated_header"

    def test_swagger_generated_header(self) -> None:
        rule = next(r for r in DEFAULT_RULES if r.name == "openapi_generated_header")
        detector = BoilerplateDetector(rules=[rule])
        result = detector.matching_rule(
            "// This class is auto generated by Swagger Codegen"
        )
        assert result == "openapi_generated_header"

    def test_terraform_lock_hash(self) -> None:
        detector = BoilerplateDetector()
        # exactly 43 base64 chars + trailing '='
        result = detector.matching_rule(
            "h1:abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQ="
        )
        assert result == "terraform_lock_hash"

    def test_clean_content_returns_none(self) -> None:
        detector = BoilerplateDetector()
        result = detector.matching_rule("def solve_problem(n: int) -> int:\n    return n * 2")
        assert result is None

    def test_empty_string_returns_none(self) -> None:
        detector = BoilerplateDetector()
        assert detector.matching_rule("") is None


# ---------------------------------------------------------------------------
# BoilerplateDetector — filter
# ---------------------------------------------------------------------------


class TestFilter:
    def test_boilerplate_chunk_is_removed(self) -> None:
        detector = BoilerplateDetector()
        chunks = [_chunk("c1", "// SPDX-License-Identifier: Apache-2.0")]
        kept, removed = detector.filter(chunks)
        assert kept == []
        assert len(removed) == 1
        assert removed[0].chunk_id == "c1"
        assert removed[0].reason == RemovalReason.BOILERPLATE
        assert removed[0].boilerplate_rule == "spdx_license_header"

    def test_clean_chunk_is_kept(self) -> None:
        detector = BoilerplateDetector()
        chunks = [_chunk("c2", "def foo(): return 42")]
        kept, removed = detector.filter(chunks)
        assert len(kept) == 1
        assert removed == []

    def test_removed_chunk_has_original_content(self) -> None:
        content = "// SPDX-License-Identifier: MIT\nsome code"
        detector = BoilerplateDetector()
        _, removed = detector.filter([_chunk("c3", content)])
        assert removed[0].original_content == content

    def test_mixed_chunks_partitioned_correctly(self) -> None:
        detector = BoilerplateDetector()
        chunks = [
            _chunk("clean1", "def add(a, b): return a + b"),
            _chunk("bp1", "// SPDX-License-Identifier: MIT"),
            _chunk("clean2", "class Foo: pass"),
            _chunk("bp2", "// This file was generated — DO NOT EDIT"),
        ]
        kept, removed = detector.filter(chunks)
        assert [c.chunk_id for c in kept] == ["clean1", "clean2"]
        assert [r.chunk_id for r in removed] == ["bp1", "bp2"]

    def test_empty_input_returns_empty_lists(self) -> None:
        detector = BoilerplateDetector()
        kept, removed = detector.filter([])
        assert kept == []
        assert removed == []


# ---------------------------------------------------------------------------
# BoilerplateDetector — custom rules
# ---------------------------------------------------------------------------


class TestCustomRules:
    def test_custom_rule_matches(self) -> None:
        rules = [BoilerplateRule(name="acme_header", pattern=r"ACME CORP CONFIDENTIAL")]
        detector = BoilerplateDetector(rules=rules)
        assert detector.matching_rule("ACME CORP CONFIDENTIAL — internal use only") == "acme_header"

    def test_disabled_rule_is_skipped(self) -> None:
        rules = [
            BoilerplateRule(name="active", pattern=r"ONLY_ACTIVE_MARKER"),
            BoilerplateRule(name="inactive", pattern=r"ONLY_INACTIVE_MARKER", enabled=False),
        ]
        detector = BoilerplateDetector(rules=rules)
        assert detector.matching_rule("ONLY_INACTIVE_MARKER content") is None
        assert detector.matching_rule("ONLY_ACTIVE_MARKER content") == "active"

    def test_patterns_precompiled_at_init(self) -> None:
        detector = BoilerplateDetector()
        import re

        assert all(
            isinstance(pat, re.Pattern) for _, pat in detector._compiled
        )


# ---------------------------------------------------------------------------
# BoilerplateSettings — env-var rule extension
# ---------------------------------------------------------------------------


class TestBoilerplateSettings:
    def test_extra_rule_added_via_env(self, monkeypatch: pytest.MonkeyPatch) -> None:
        monkeypatch.setenv("BOILERPLATE_EXTRA_RULES", "my_rule|ACME CORP CONFIDENTIAL")
        settings = BoilerplateSettings()
        rules = settings.get_rules()
        names = [r.name for r in rules]
        assert "my_rule" in names

    def test_disabled_rule_set_to_inactive(self, monkeypatch: pytest.MonkeyPatch) -> None:
        monkeypatch.setenv("BOILERPLATE_DISABLED_RULES", "maven_build_output")
        settings = BoilerplateSettings()
        rules = settings.get_rules()
        maven_rule = next(r for r in rules if r.name == "maven_build_output")
        assert maven_rule.enabled is False

    def test_disabled_rule_not_matched_by_detector(
        self, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        monkeypatch.setenv("BOILERPLATE_DISABLED_RULES", "maven_build_output")
        settings = BoilerplateSettings()
        detector = BoilerplateDetector(rules=settings.get_rules())
        assert detector.matching_rule("[INFO] --- maven-compiler-plugin") is None

    def test_multiple_extra_rules_semicolon_separated(
        self, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        monkeypatch.setenv(
            "BOILERPLATE_EXTRA_RULES",
            "rule_a|PATTERN_A;rule_b|PATTERN_B",
        )
        settings = BoilerplateSettings()
        rules = settings.get_rules()
        names = [r.name for r in rules]
        assert "rule_a" in names
        assert "rule_b" in names

    def test_default_settings_returns_all_default_rules(self) -> None:
        settings = BoilerplateSettings(
            boilerplate_extra_rules="",
            boilerplate_disabled_rules="",
        )
        rules = settings.get_rules()
        assert len(rules) == len(DEFAULT_RULES)

    def test_multiple_disabled_rules_comma_separated(
        self, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        monkeypatch.setenv(
            "BOILERPLATE_DISABLED_RULES", "maven_build_output,package_lock_metadata"
        )
        settings = BoilerplateSettings()
        rules = settings.get_rules()
        disabled = {r.name for r in rules if not r.enabled}
        assert "maven_build_output" in disabled
        assert "package_lock_metadata" in disabled
