apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "contextiq-common.fullname" . }}-config
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "contextiq-common.labels" . | nindent 4 }}
data:
  {{- range $k, $v := .Values.config }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
