"""Boilerplate rule model and default registry (AIR-013 baseline patterns)."""

from __future__ import annotations

import re

from pydantic import BaseModel, field_validator


class BoilerplateRule(BaseModel):
    """Named regex rule tested against chunk content to identify boilerplate."""

    name: str
    pattern: str
    description: str = ""
    enabled: bool = True

    @field_validator("pattern")
    @classmethod
    def pattern_compiles(cls, v: str) -> str:
        """Validate that the pattern is a compilable regex."""
        try:
            re.compile(v, re.IGNORECASE | re.MULTILINE)
        except re.error as exc:
            raise ValueError(f"Invalid regex pattern: {exc}") from exc
        return v


DEFAULT_RULES: list[BoilerplateRule] = [
    BoilerplateRule(
        name="spdx_license_header",
        pattern=r"SPDX-License-Identifier:",
        description="SPDX licence identifier comment",
    ),
    BoilerplateRule(
        name="copyright_header",
        pattern=r"^\s*[/#*]+\s*Copyright\s+\(c\)",
        description="Copyright notice block at file start",
    ),
    BoilerplateRule(
        name="auto_generated_warning",
        pattern=r"(DO NOT EDIT|AUTO[- ]?GENERATED|This file was generated)",
        description="Auto-generated file header warning",
    ),
    BoilerplateRule(
        name="maven_build_output",
        pattern=r"^\[INFO\]\s+---\s+maven",
        description="Maven build log output lines",
    ),
    BoilerplateRule(
        name="package_lock_metadata",
        pattern=r'"integrity":\s*"sha(256|512)-',
        description="npm package-lock.json integrity hash entries",
    ),
    BoilerplateRule(
        name="generated_proto_header",
        pattern=r"Code generated by protoc-gen",
        description="Protocol Buffer generated file header",
    ),
    BoilerplateRule(
        name="openapi_generated_header",
        pattern=r"This class is auto generated by (OpenAPI|Swagger)",
        description="OpenAPI/Swagger generated client header",
    ),
    BoilerplateRule(
        name="terraform_lock_hash",
        pattern=r"h1:[A-Za-z0-9+/]{43}=",
        description="Terraform dependency lock file hash entries",
    ),
]
