#!/bin/bash
# entrypoint.sh — ContextIQ local Kafka broker bootstrap.
#
# Runs as root; builds PKCS12 keystore/truststore from the shared TLS certs,
# writes a JAAS config for SASL SCRAM-SHA-512, renders server.properties for
# a single-node KRaft broker+controller, formats storage on first boot
# (bootstrapping the SCRAM user), then execs kafka-server-start.sh as
# the unprivileged `appuser`.

set -euo pipefail

DATA_DIR="/var/lib/kafka/data"
CERT_DIR="/opt/kafka/config/certs"
TLS_SRC="/tls"
KEYSTORE_PASSWORD="${KAFKA_TLS_KEYSTORE_PASSWORD:-kafka_dev}"
KAFKA_USERNAME="${KAFKA_USERNAME:-contextiq}"
KAFKA_PASSWORD="${KAFKA_PASSWORD:-contextiq_dev}"
CLUSTER_ID="${KAFKA_CLUSTER_ID:-dGVzdC1sb2NhbC1rYWZrYQ}"

mkdir -p "$DATA_DIR" "$CERT_DIR"
chown -R appuser:appuser "$DATA_DIR" "$CERT_DIR" /opt/kafka/config

# ── Wait for TLS certs generated by the cert-init service ───────────────────
until [ -f "$TLS_SRC/kafka.crt" ] && [ -f "$TLS_SRC/kafka.key" ] && [ -f "$TLS_SRC/ca.crt" ]; do
    echo "[kafka-entrypoint] Waiting for TLS certificates..."
    sleep 2
done

# ── Build PKCS12 keystore/truststore (idempotent) ───────────────────────────
if [ ! -f "$CERT_DIR/kafka.keystore.p12" ]; then
    echo "[kafka-entrypoint] Building PKCS12 keystore..."
    openssl pkcs12 -export \
        -in "$TLS_SRC/kafka.crt" -inkey "$TLS_SRC/kafka.key" \
        -certfile "$TLS_SRC/ca.crt" \
        -name kafka -out "$CERT_DIR/kafka.keystore.p12" \
        -passout "pass:${KEYSTORE_PASSWORD}"
fi
if [ ! -f "$CERT_DIR/kafka.truststore.p12" ]; then
    echo "[kafka-entrypoint] Building PKCS12 truststore..."
    # keytool -importcert (not openssl) correctly marks the CA as a trusted
    # entry; `openssl pkcs12 -export -nokeys` alone produces a truststore
    # with zero trust anchors, which Java's SSLContext rejects at runtime.
    keytool -importcert -noprompt \
        -alias ca -file "$TLS_SRC/ca.crt" \
        -keystore "$CERT_DIR/kafka.truststore.p12" \
        -storetype PKCS12 -storepass "$KEYSTORE_PASSWORD"
fi
chown appuser:appuser "$CERT_DIR"/*.p12

# ── JAAS config for SASL SCRAM-SHA-512 ──────────────────────────────────────
cat > /opt/kafka/config/kafka_server_jaas.conf <<'EOF'
KafkaServer {
  org.apache.kafka.common.security.scram.ScramLoginModule required;
};
EOF
chown appuser:appuser /opt/kafka/config/kafka_server_jaas.conf

# ── Render server.properties for single-node KRaft broker+controller ───────
cat > /opt/kafka/config/server.properties <<EOF
process.roles=broker,controller
node.id=1
controller.quorum.voters=1@localhost:9093

listeners=SASL_SSL://:9092,CONTROLLER://:9093
inter.broker.listener.name=SASL_SSL
advertised.listeners=SASL_SSL://kafka:9092
controller.listener.names=CONTROLLER
listener.security.protocol.map=CONTROLLER:PLAINTEXT,SASL_SSL:SASL_SSL

sasl.enabled.mechanisms=SCRAM-SHA-512
sasl.mechanism.inter.broker.protocol=SCRAM-SHA-512

ssl.keystore.location=${CERT_DIR}/kafka.keystore.p12
ssl.keystore.password=${KEYSTORE_PASSWORD}
ssl.key.password=${KEYSTORE_PASSWORD}
ssl.keystore.type=PKCS12
ssl.truststore.location=${CERT_DIR}/kafka.truststore.p12
ssl.truststore.password=${KEYSTORE_PASSWORD}
ssl.truststore.type=PKCS12
ssl.client.auth=none

log.dirs=${DATA_DIR}
num.partitions=1
auto.create.topics.enable=false
log.retention.hours=168
offsets.topic.replication.factor=1
transaction.state.log.replication.factor=1
transaction.state.log.min.isr=1
num.network.threads=3
num.io.threads=8
socket.send.buffer.bytes=102400
socket.receive.buffer.bytes=102400
socket.request.max.bytes=104857600
num.recovery.threads.per.data.dir=1
log.segment.bytes=1073741824
log.retention.check.interval.ms=300000
EOF
chown appuser:appuser /opt/kafka/config/server.properties

# ── Format storage on first boot only (bootstraps the SCRAM user) ──────────
if [ ! -f "$DATA_DIR/meta.properties" ]; then
    echo "[kafka-entrypoint] Formatting KRaft storage (first boot)..."
    su-exec appuser /opt/kafka/bin/kafka-storage.sh format \
        --add-scram "SCRAM-SHA-512=[name=${KAFKA_USERNAME},password=${KAFKA_PASSWORD}]" \
        --cluster-id "$CLUSTER_ID" \
        -c /opt/kafka/config/server.properties \
        --ignore-formatted
fi

export KAFKA_OPTS="-Djava.security.auth.login.config=/opt/kafka/config/kafka_server_jaas.conf"

echo "[kafka-entrypoint] Starting Kafka broker..."
exec su-exec appuser /opt/kafka/bin/kafka-server-start.sh /opt/kafka/config/server.properties
