apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "contextiq-common.serviceAccountName" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "contextiq-common.labels" . | nindent 4 }}
automountServiceAccountToken: false
