"""Prompt merger for clarification re-submission — TASK-US011-04.

Provides ``merge_prompt()``, which combines the original user request,
the clarification question generated by the pipeline, and the user's
answer into a single enriched prompt.  The merged text is passed to
the ``intent_agent`` on the second-pass invocation so the classifier
has full context.
"""
from __future__ import annotations

MERGE_TEMPLATE = """\
[Original request]
{original_prompt}

[Clarification asked]
{clarification_question}

[User clarification]
{user_clarification}
"""


def merge_prompt(
    original_prompt: str,
    clarification_question: str,
    user_clarification: str,
) -> str:
    """Produce a single enriched prompt that gives the classifier full context.

    Args:
        original_prompt: The raw user prompt from the first pipeline pass.
        clarification_question: The question generated by the clarification node.
        user_clarification: The user's answer to the clarification question.

    Returns:
        A structured string combining all three sections.
    """
    return MERGE_TEMPLATE.format(
        original_prompt=original_prompt.strip(),
        clarification_question=clarification_question.strip(),
        user_clarification=user_clarification.strip(),
    )
