apiVersion: v2
name:        istiod
description: Istio control plane for ContextIQ
type:        application
version:     0.1.0
dependencies:
  - name:       istiod
    version:    "1.22.3"
    repository: https://istio-release.storage.googleapis.com/charts
